// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package common

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 1-99	常见公用错误码
func IsErrCodeNone(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrCode_ErrCodeNone.String() && e.Code == 520
}

// 1-99	常见公用错误码
func ErrorErrCodeNone(format string, args ...interface{}) *errors.Error {
	return errors.New(520, ErrCode_ErrCodeNone.String(), fmt.Sprintf(format, args...))
}

// 非法参数
func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrCode_InvalidParams.String() && e.Code == 520
}

// 非法参数
func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(520, ErrCode_InvalidParams.String(), fmt.Sprintf(format, args...))
}

// redis错误
func IsRedisError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrCode_RedisError.String() && e.Code == 520
}

// redis错误
func ErrorRedisError(format string, args ...interface{}) *errors.Error {
	return errors.New(520, ErrCode_RedisError.String(), fmt.Sprintf(format, args...))
}

// token失效
func IsTokenFailure(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrCode_TokenFailure.String() && e.Code == 520
}

// token失效
func ErrorTokenFailure(format string, args ...interface{}) *errors.Error {
	return errors.New(520, ErrCode_TokenFailure.String(), fmt.Sprintf(format, args...))
}

// riak错误
func IsRiakError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrCode_RiakError.String() && e.Code == 520
}

// riak错误
func ErrorRiakError(format string, args ...interface{}) *errors.Error {
	return errors.New(520, ErrCode_RiakError.String(), fmt.Sprintf(format, args...))
}
