// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: common/error.proto

package common

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	// 1-99	常见公用错误码
	ErrCode_ErrCodeNone         ErrCode = 0
	ErrCode_InvalidParams       ErrCode = 1  //非法参数
	ErrCode_RedisError          ErrCode = 2  //redis错误
	ErrCode_TokenFailure        ErrCode = 3  //token失效
	ErrCode_RiakError           ErrCode = 4  //riak错误
	ErrCode_InvalidMerchantName ErrCode = 48 // merchantName wrong
	ErrCode_InvalidMerchantCode ErrCode = 49 // merchantCode wrong
	ErrCode_MerchantNameLock    ErrCode = 50 // merchant被锁
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:  "ErrCodeNone",
		1:  "InvalidParams",
		2:  "RedisError",
		3:  "TokenFailure",
		4:  "RiakError",
		48: "InvalidMerchantName",
		49: "InvalidMerchantCode",
		50: "MerchantNameLock",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNone":         0,
		"InvalidParams":       1,
		"RedisError":          2,
		"TokenFailure":        3,
		"RiakError":           4,
		"InvalidMerchantName": 48,
		"InvalidMerchantCode": 49,
		"MerchantNameLock":    50,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_error_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_common_error_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

// 客户端只接受proto, 目前服务器推下来的错误信息,是json格式的，加个错误的message,用来解析json
type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_common_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_common_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorMsg) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_error_proto protoreflect.FileDescriptor

var file_common_error_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x13, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x50, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0xd4, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x1a, 0x03, 0xa8, 0x45, 0x00, 0x12, 0x16, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x10, 0x01, 0x1a, 0x03, 0xa8, 0x45, 0x01, 0x12, 0x13, 0x0a,
	0x0a, 0x52, 0x65, 0x64, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x1a, 0x03, 0xa8,
	0x45, 0x02, 0x12, 0x15, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x10, 0x03, 0x1a, 0x03, 0xa8, 0x45, 0x03, 0x12, 0x12, 0x0a, 0x09, 0x52, 0x69, 0x61,
	0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x1a, 0x03, 0xa8, 0x45, 0x04, 0x12, 0x1c, 0x0a,
	0x13, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x10, 0x30, 0x1a, 0x03, 0xa8, 0x45, 0x30, 0x12, 0x1c, 0x0a, 0x13, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x10, 0x31, 0x1a, 0x03, 0xa8, 0x45, 0x31, 0x12, 0x19, 0x0a, 0x10, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x10, 0x32, 0x1a,
	0x03, 0xa8, 0x45, 0x32, 0x1a, 0x04, 0xa0, 0x45, 0x88, 0x04, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x74, 0x65, 0x72, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x2f, 0x73, 0x70, 0x67, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_error_proto_rawDescOnce sync.Once
	file_common_error_proto_rawDescData = file_common_error_proto_rawDesc
)

func file_common_error_proto_rawDescGZIP() []byte {
	file_common_error_proto_rawDescOnce.Do(func() {
		file_common_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_error_proto_rawDescData)
	})
	return file_common_error_proto_rawDescData
}

var file_common_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_error_proto_goTypes = []interface{}{
	(ErrCode)(0),     // 0: common.ErrCode
	(*ErrorMsg)(nil), // 1: common.ErrorMsg
}
var file_common_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_error_proto_init() }
func file_common_error_proto_init() {
	if File_common_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_error_proto_goTypes,
		DependencyIndexes: file_common_error_proto_depIdxs,
		EnumInfos:         file_common_error_proto_enumTypes,
		MessageInfos:      file_common_error_proto_msgTypes,
	}.Build()
	File_common_error_proto = out.File
	file_common_error_proto_rawDesc = nil
	file_common_error_proto_goTypes = nil
	file_common_error_proto_depIdxs = nil
}
