// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v3.21.2
// source: notice/test_api.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTestSendMessage = "/third_party_notice.Test/SendMessage"

type TestHTTPServer interface {
	// SendMessage 发送消息
	SendMessage(context.Context, *SendMessageReq) (*Empty, error)
}

func RegisterTestHTTPServer(s *http.Server, srv TestHTTPServer) {
	r := s.Route("/")
	r.POST("third-party-notice/test/SendMessage", _Test_SendMessage0_HTTP_Handler(srv))
}

func _Test_SendMessage0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTestSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

type TestHTTPClient interface {
	SendMessage(ctx context.Context, req *SendMessageReq, opts ...http.CallOption) (rsp *Empty, err error)
}

type TestHTTPClientImpl struct {
	cc *http.Client
}

func NewTestHTTPClient(client *http.Client) TestHTTPClient {
	return &TestHTTPClientImpl{client}
}

func (c *TestHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageReq, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "third-party-notice/test/SendMessage"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTestSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
